version: "3"
services:
  selenium-hub:
    image: selenium/standalone-chrome:4.18.0
    ports:
      - "4444:4444"
    shm_size: 2gb

  test-runner:
    build: .
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
    command: mvn test -Denv=qa -DsuiteXmlFile=testng.xml
